/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTerminosRouteImport } from './routes/legal.terminos'
import { Route as LegalPrivacidadRouteImport } from './routes/legal.privacidad'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppEstimadosRouteImport } from './routes/_app.estimados'
import { Route as AppAvisosRouteImport } from './routes/_app.avisos'
import { Route as AppFlotaIndexRouteImport } from './routes/_app.flota.index'
import { Route as AppFlotaVehicleIdRouteImport } from './routes/_app.flota.$vehicleId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTerminosRoute = LegalTerminosRouteImport.update({
  id: '/legal/terminos',
  path: '/legal/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacidadRoute = LegalPrivacidadRouteImport.update({
  id: '/legal/privacidad',
  path: '/legal/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppEstimadosRoute = AppEstimadosRouteImport.update({
  id: '/estimados',
  path: '/estimados',
  getParentRoute: () => AppRoute,
} as any)
const AppAvisosRoute = AppAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AppRoute,
} as any)
const AppFlotaIndexRoute = AppFlotaIndexRouteImport.update({
  id: '/flota/',
  path: '/flota/',
  getParentRoute: () => AppRoute,
} as any)
const AppFlotaVehicleIdRoute = AppFlotaVehicleIdRouteImport.update({
  id: '/flota/$vehicleId',
  path: '/flota/$vehicleId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/setup': typeof SetupRoute
  '/avisos': typeof AppAvisosRoute
  '/estimados': typeof AppEstimadosRoute
  '/home': typeof AppHomeRoute
  '/perfil': typeof AppPerfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/flota/$vehicleId': typeof AppFlotaVehicleIdRoute
  '/flota/': typeof AppFlotaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/setup': typeof SetupRoute
  '/avisos': typeof AppAvisosRoute
  '/estimados': typeof AppEstimadosRoute
  '/home': typeof AppHomeRoute
  '/perfil': typeof AppPerfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/flota/$vehicleId': typeof AppFlotaVehicleIdRoute
  '/flota': typeof AppFlotaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/setup': typeof SetupRoute
  '/_app/avisos': typeof AppAvisosRoute
  '/_app/estimados': typeof AppEstimadosRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/_app/flota/$vehicleId': typeof AppFlotaVehicleIdRoute
  '/_app/flota/': typeof AppFlotaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/intro'
    | '/login'
    | '/onboarding'
    | '/setup'
    | '/avisos'
    | '/estimados'
    | '/home'
    | '/perfil'
    | '/auth/callback'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/flota/$vehicleId'
    | '/flota/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/intro'
    | '/login'
    | '/onboarding'
    | '/setup'
    | '/avisos'
    | '/estimados'
    | '/home'
    | '/perfil'
    | '/auth/callback'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/flota/$vehicleId'
    | '/flota'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/intro'
    | '/login'
    | '/onboarding'
    | '/setup'
    | '/_app/avisos'
    | '/_app/estimados'
    | '/_app/home'
    | '/_app/perfil'
    | '/auth/callback'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/_app/flota/$vehicleId'
    | '/_app/flota/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  IntroRoute: typeof IntroRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SetupRoute: typeof SetupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  LegalPrivacidadRoute: typeof LegalPrivacidadRoute
  LegalTerminosRoute: typeof LegalTerminosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terminos': {
      id: '/legal/terminos'
      path: '/legal/terminos'
      fullPath: '/legal/terminos'
      preLoaderRoute: typeof LegalTerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacidad': {
      id: '/legal/privacidad'
      path: '/legal/privacidad'
      fullPath: '/legal/privacidad'
      preLoaderRoute: typeof LegalPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estimados': {
      id: '/_app/estimados'
      path: '/estimados'
      fullPath: '/estimados'
      preLoaderRoute: typeof AppEstimadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avisos': {
      id: '/_app/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AppAvisosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flota/': {
      id: '/_app/flota/'
      path: '/flota'
      fullPath: '/flota/'
      preLoaderRoute: typeof AppFlotaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flota/$vehicleId': {
      id: '/_app/flota/$vehicleId'
      path: '/flota/$vehicleId'
      fullPath: '/flota/$vehicleId'
      preLoaderRoute: typeof AppFlotaVehicleIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAvisosRoute: typeof AppAvisosRoute
  AppEstimadosRoute: typeof AppEstimadosRoute
  AppHomeRoute: typeof AppHomeRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppFlotaVehicleIdRoute: typeof AppFlotaVehicleIdRoute
  AppFlotaIndexRoute: typeof AppFlotaIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvisosRoute: AppAvisosRoute,
  AppEstimadosRoute: AppEstimadosRoute,
  AppHomeRoute: AppHomeRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppFlotaVehicleIdRoute: AppFlotaVehicleIdRoute,
  AppFlotaIndexRoute: AppFlotaIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  IntroRoute: IntroRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SetupRoute: SetupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  LegalPrivacidadRoute: LegalPrivacidadRoute,
  LegalTerminosRoute: LegalTerminosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
